# Generated by Django 4.1.1 on 2022-09-11 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Generico', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Generico', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_p', models.CharField(max_length=20)),
                ('nombre_p', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('cuidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(default='descripcion')),
                ('precio', models.PositiveIntegerField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='core/images/')),
                ('estado', models.BooleanField(default=False)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('almacen', models.CharField(blank=True, max_length=150, null=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=50, null=True)),
                ('codigo', models.PositiveIntegerField()),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_compra', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('neto', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('autor', models.CharField(blank=True, max_length=50, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedor')),
                ('related_productos', models.ManyToManyField(blank=True, to='core.producto')),
            ],
        ),
    ]
