# Generated by Django 4.1.1 on 2022-10-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="last_cs_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="last_cs_user",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="last_mod_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="last_mod_user",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="factura",
            name="codigo",
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
