# Generated by Django 3.2.3 on 2022-09-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='serie',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
