# Generated by Django 4.1.1 on 2022-10-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_producto_last_cs_time_producto_last_cs_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
    ]
