# Generated by Django 4.1.1 on 2022-10-01 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_producto_descripcion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producto",
            old_name="descripcion",
            new_name="observacion",
        ),
    ]
